[window]
padding = { x = 10, y = 10 }
dynamic_padding = true
opacity = 0.80

[font]
size = 9.0
normal = { family = "MesloLGMDZ Nerd Font", style = "Regular" }
bold = { family = "MesloLGMDZ Nerd Font", style = "Bold" }
italic = { family = "MesloLGMDZ Nerd Font", style = "Italic" }
bold_italic = { family = "MesloLGMDZ Nerd Font", style = "Bold Italic" }

[bell]
animation = "Ease"

[env]
TERM = "xterm-256color"
